-- =====================================================
-- HELPDESK TICKETING SYSTEM DATABASE SCHEMA
-- =====================================================

-- USERS TABLE
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- =====================================================

-- AGENTS TABLE
CREATE TABLE AGENTS (
    AGENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- =====================================================

-- TICKETS TABLE
CREATE TABLE TICKETS (
    TICKET_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    TITLE VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(2000),

    PRIORITY VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    RESOLVED_AT TIMESTAMP,

    USER_ID NUMBER NOT NULL,
    AGENT_ID NUMBER,

    CONSTRAINT FK_TICKET_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_TICKET_AGENT
        FOREIGN KEY (AGENT_ID)
        REFERENCES AGENTS(AGENT_ID)
);

-- =====================================================

-- COMMENTS TABLE
CREATE TABLE COMMENTS (
    COMMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    MESSAGE VARCHAR2(2000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,

    TICKET_ID NUMBER NOT NULL,

    CONSTRAINT FK_COMMENT_TICKET
        FOREIGN KEY (TICKET_ID)
        REFERENCES TICKETS(TICKET_ID)
);

-- =====================================================

-- TICKET STATUS HISTORY TABLE
CREATE TABLE TICKET_STATUS_HISTORY (
    HISTORY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    OLD_STATUS VARCHAR2(20) NOT NULL,
    NEW_STATUS VARCHAR2(20) NOT NULL,

    CHANGED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,

    TICKET_ID NUMBER NOT NULL,

    CONSTRAINT FK_HISTORY_TICKET
        FOREIGN KEY (TICKET_ID)
        REFERENCES TICKETS(TICKET_ID)
);

-- =====================================================
-- CHECK CONSTRAINTS
-- =====================================================

ALTER TABLE TICKETS
ADD CONSTRAINT CHK_TICKET_PRIORITY
CHECK (
    PRIORITY IN (
        'LOW',
        'MEDIUM',
        'HIGH',
        'CRITICAL'
    )
);

ALTER TABLE TICKETS
ADD CONSTRAINT CHK_TICKET_STATUS
CHECK (
    STATUS IN (
        'OPEN',
        'IN_PROGRESS',
        'RESOLVED',
        'CLOSED',
        'REOPENED'
    )
);

ALTER TABLE TICKETS
ADD CONSTRAINT CHK_TICKET_CATEGORY
CHECK (
    CATEGORY IN (
        'HARDWARE',
        'SOFTWARE',
        'NETWORK',
        'EMAIL',
        'SECURITY',
        'ACCESS',
        'OTHER'
    )
);
```
